import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

const translations: { [lang: string]: { [key: string]: string } } = {
    en: {
        dashboard: 'Dashboard',
        products: 'Products',
        sales: 'Sales',
        suppliers: 'Suppliers',
        expenses: 'Expenses',
        customers: 'Customers',
        reports: 'Reports',
        settings: 'Settings',
        product_management: 'Product Management',
        product_name: 'Product Name',
        product_image: 'Product Image',
        category: 'Category',
        stock: 'Stock',
        buying_price: 'Buying Price',
        selling_price: 'Selling Price',
        size: 'Size',
        color: 'Color',
        supplier: 'Supplier',
        barcode: 'Barcode',
        save_product: 'Save Product',
        clear_form: 'Clear Form',
        product_list: 'Product List',
        search_products: 'Search products...',
        total_sales: 'Total Sales',
        total_profit: 'Total Profit',
        total_products: 'Total Products',
        credit_payments: 'Credit Payments',
        sales_trends: 'Sales Trends',
        profit_trends: 'Profit Trends',
        top_5_best_selling: 'Top 5 Best-Selling Products',
        sales_by_category: 'Sales by Category',
        customer: 'Customer',
        walk_in_customer: 'Walk-in Customer',
        online_customer: 'Online Customer',
        search: 'Search',
        discount_percent: 'Discount (%)',
        current_sale: 'Current Sale',
        cart_total: 'Total',
        clear_cart: 'Clear Cart',
        receipt: 'Receipt',
        payment: 'Payment',
        order_discount: 'Order Discount (%)',
        payment_method: 'Payment Method',
        cash: 'Cash',
        credit: 'Credit',
        bank_transfer: 'Bank Transfer',
        amount_paid: 'Amount Paid',
        change: 'Change',
        notes: 'Notes',
        complete_sale: 'Complete Sale',
        print_receipt: 'Print Receipt',
        supplier_management: 'Supplier Management',
        supplier_name: 'Supplier Name',
        phone_number: 'Phone Number',
        email: 'Email',
        address: 'Address',
        save_supplier: 'Save Supplier',
        supplier_list: 'Supplier List',
        search_suppliers: 'Search suppliers...',
        expense_management: 'Expense Management',
        expense_category: 'Category',
        amount_mmk: 'Amount',
        date: 'Date',
        description: 'Description',
        save_expense: 'Save Expense',
        expense_list: 'Expense List',
        search_expenses: 'Search expenses...',
        customer_management: 'Customer Management',
        customer_name: 'Customer Name',
        save_customer: 'Save Customer',
        customer_list: 'Customer List',
        search_customers: 'Search customers...',
        reports_management: 'Reports',
        report_type: 'Report Type',
        sales_report: 'Sales Report',
        inventory_report: 'Inventory Report',
        profit_report: 'Profit & Loss Report',
        expenses_report: 'Expenses Report',
        start_date: 'Start Date',
        end_date: 'End Date',
        generate_report: 'Generate Report',
        export_to_excel: 'Export to Excel',
        settings_management: 'Settings',
        company_information: 'Company Information',
        company_name: 'Company Name',
        company_logo: 'Company Logo',
        save_company_info: 'Save Company Info',
        system_settings: 'System Settings',
        language: 'Language',
        currency: 'Currency',
        tax_rate: 'Tax Rate (%)',
        enable_notifications: 'Enable Notifications',
        enable_sound_effects: 'Enable Sound Effects',
        save_system_settings: 'Save System Settings',
        export_backup_json: 'Export Backup (JSON)',
        import_backup_json: 'Import Backup (JSON)',
        reset_data: 'Reset All Data',
        report_results: 'Report Results',
        generate_report_to_see_results: 'Generate a report to see results',
        business_type: 'Business Type',
        clothing_business: 'Clothing',
        pharmacy_business: 'Pharmacy',
        convenience_business: 'Convenience',
        hardware_business: 'Hardware',
        footer_text: '© 2024 Swift POS. All rights reserved.',
        scan_barcode_title: 'Scan Barcode',
        btn_close_scanner: 'Close Scanner',
        btn_scan_barcode: 'Scan',
        barcode_detected: 'Barcode detected',
        product_found_and_loaded: 'Product found and loaded for editing.',
        actions: 'Actions',
        'Category Management': 'Category Management',
        'Add New Category': 'Add New Category',
        'Update Category': 'Update Category',
        'Category Name': 'Category Name',
        'Are you sure you want to delete this category?': 'Are you sure you want to delete this category?',
        'expenses_by_category': 'Expenses by Category',
        'recent_supplier_payments': 'Recent Supplier Payments',
        'Payment History for': 'Payment History for',
        'View Payments': 'View Payments',
        'No payments found.': 'No payments found.',
        'Total COGS': 'Total Cost of Goods Sold',
        'Gross Profit': 'Gross Profit',
        'Total Expenses': 'Total Expenses',
        'Net Profit': 'Net Profit',
        'Report for': 'Report for',
        'Inventory Value': 'Inventory Value',
        'Select Supplier': 'Select Supplier',
        'Edit': 'Edit',
        'Delete': 'Delete',
        'Go to Settings to add categories.': 'Go to Settings to add categories.',
        'Enter new category name': 'Enter new category name',
        'Cancel': 'Cancel',
        'Save': 'Save',
        'record_payment': 'Record Payment',
        'add_payment': 'Add Payment',
        'new_payment_for': 'New Payment for',
        'customer_credit_balance': 'Credit Balance',
        'total_credit': 'Total Credit',
        'total_paid': 'Total Paid',
        'balance': 'Balance',
        'credit_history': 'Credit History',
        'credit_sale_customer_required': 'A registered customer must be selected for credit sales.',
        'supplier_payment_form': 'Record Supplier Payment',
        'payment_to': 'Payment To',
        'credit_sales': 'Credit Sales',
        'customer_payments': 'Customer Payments',
        'No payments recorded.': 'No payments recorded.',
        'low_stock_threshold': 'Low Stock Threshold',
        'purchase_suggestions': 'Purchase Suggestions',
        'current_stock': 'Current Stock',
        'record_customer_payment': 'Record Customer Payment',
        'No low stock products.': 'No low stock products.',
        'Select Customer': 'Select Customer',
        'Add Customer': 'Add Customer',
        'Edit Customer': 'Edit Customer',
        receipt_settings: 'Receipt Settings',
        receipt_size: 'Receipt Size',
        standard_print: 'Standard (A4/Letter)',
        thermal_80mm: '80mm Thermal Printer',
        thermal_58mm: '58mm Thermal Printer',
        receipt_footer_text: 'Receipt Footer Text',
        todays_sales: "Today's Sales",
        void_sale: 'Void',
        load_to_cart_for_edit: 'This will void the original sale and load its items into the cart for editing. Continue?',
        are_you_sure_void_sale: 'Are you sure you want to void this sale? This will restock items and cannot be undone.',
        sale_voided_successfully: 'Sale voided successfully.',
        sale_loaded_for_edit: 'Sale loaded into cart for editing.',
        edit_expense: 'Edit Expense',
        confirm_delete_expense: 'Are you sure you want to delete this expense?',
        customer_details: 'Customer Details',
        items_purchased: 'Items Purchased',
        total_amount: 'Total Amount',
        confirm_void: 'Confirm Void',
        folder_selection_disabled_in_environment: 'Folder selection is disabled in this sandboxed environment. Backups will download normally.',
        storage_preferences: 'Storage Preferences',
        local_folder: 'Local Folder',
        online_folder_url: 'Online Folder (URL)',
        path_or_url: 'Path or URL',
        choose_folder: 'Choose Folder',
        save_storage_preference: 'Save Storage Preference',
        path_or_url_placeholder: '/Users/me/Documents or https://drive.google.com/...',
        data_management: 'Data Management',
        sales_history: 'Sales History',
        no_sales_found_for_period: 'No sales found for the selected period.',
        all_categories: 'All Categories',
        date_range: 'Date Range',
    },
    my: {
        dashboard: 'ဒိုင်ခွက်',
        products: 'ကုန်ပစ္စည်းများ',
        sales: 'အရောင်း',
        suppliers: 'ကုန်သွင်းသူများ',
        expenses: 'ကုန်ကျစရိတ်',
        customers: 'ဖောက်သည်များ',
        reports: 'အစီရင်ခံစာများ',
        settings: 'ဆက်တင်များ',
        product_management: 'ကုန်ပစ္စည်း စီမံခန့်ခွဲမှု',
        product_name: 'ကုန်ပစ္စည်းအမည်',
        product_image: 'ကုန်ပစ္စည်းပုံ',
        category: 'အမျိုးအစား',
        stock: 'စတော့',
        buying_price: 'ဝယ်ဈေး',
        selling_price: 'ရောင်းဈေး',
        size: 'အရွယ်အစား',
        color: 'အရောင်',
        supplier: 'ကုန်သွင်းသူ',
        barcode: 'ဘားကုဒ်',
        save_product: 'ကုန်ပစ္စည်း သိမ်းဆည်းရန်',
        clear_form: 'ဖောင်ရှင်းလင်းရန်',
        product_list: 'ကုန်ပစ္စည်းစာရင်း',
        search_products: 'ကုန်ပစ္စည်းများ ရှာဖွေရန်...',
        total_sales: 'စုစုပေါင်း အရောင်း',
        total_profit: 'စုစုပေါင်း အမြတ်',
        total_products: 'စုစုပေါင်း ကုန်ပစ္စည်း',
        credit_payments: 'အကြွေးငွေချေမှုများ',
        sales_trends: 'အရောင်းလမ်းကြောင်း',
        profit_trends: 'အမြတ်လမ်းကြောင်း',
        top_5_best_selling: 'အရောင်းရဆုံး ကုန်ပစ္စည်း ၅ ခု',
        sales_by_category: 'အမျိုးအစားအလိုက် အရောင်း',
        customer: 'ဖောက်သည်',
        walk_in_customer: 'လာရောက်ဝယ်ယူသူ',
        online_customer: 'အွန်လိုင်းဝယ်ယူသူ',
        search: 'ရှာဖွေရန်',
        discount_percent: 'လျှော့စျေး (%)',
        current_sale: 'လက်ရှိအရောင်း',
        cart_total: 'စုစုပေါင်း',
        clear_cart: 'လှည်းရှင်းလင်းရန်',
        receipt: 'ပြေစာ',
        payment: 'ငွေပေးချေမှု',
        order_discount: 'အော်ဒါ လျှော့စျေး (%)',
        payment_method: 'ငွေပေးချေနည်း',
        cash: 'ငွေသား',
        credit: 'အကြွေး',
        bank_transfer: 'ဘဏ်လွှဲ',
        amount_paid: 'ပေးချေငွေ',
        change: 'ပြန်အမ်းငွေ',
        notes: 'မှတ်စုများ',
        complete_sale: 'အရောင်းအပြီးသတ်ရန်',
        print_receipt: 'ပြေစာထုတ်ရန်',
        supplier_management: 'ကုန်သွင်းသူ စီမံခန့်ခွဲမှု',
        supplier_name: 'ကုန်သွင်းသူအမည်',
        phone_number: 'ဖုန်းနံပါတ်',
        email: 'အီးမေးလ်',
        address: 'လိပ်စာ',
        save_supplier: 'ကုန်သွင်းသူ သိမ်းဆည်းရန်',
        supplier_list: 'ကုန်သွင်းသူစာရင်း',
        search_suppliers: 'ကုန်သွင်းသူများ ရှာဖွေရန်...',
        expense_management: 'ကုန်ကျစရိတ် စီမံခန့်ခွဲမှု',
        expense_category: 'အမျိုးအစား',
        amount_mmk: 'ပမာဏ',
        date: 'ရက်စွဲ',
        description: 'အကြောင်းအရာ',
        save_expense: 'ကုန်ကျစရိတ် သိမ်းဆည်းရန်',
        expense_list: 'ကုန်ကျစရိတ်စာရင်း',
        search_expenses: 'ကုန်ကျစရိတ်များ ရှာဖွေရန်...',
        customer_management: 'ဖောက်သည် စီမံခန့်ခွဲမှု',
        customer_name: 'ဖောက်သည်အမည်',
        save_customer: 'ဖောက်သည် သိမ်းဆည်းရန်',
        customer_list: 'ဖောက်သည်စာရင်း',
        search_customers: 'ဖောက်သည်များ ရှာဖွေရန်...',
        reports_management: 'အစီရင်ခံစာများ',
        report_type: 'အစီရင်ခံစာအမျိုးအစား',
        sales_report: 'အရောင်းအစီရင်ခံစာ',
        inventory_report: 'ကုန်ပစ္စည်းစာရင်းအစီရင်ခံစာ',
        profit_report: 'အမြတ်နှင့်အရှုံး အစီရင်ခံစာ',
        expenses_report: 'ကုန်ကျစရိတ်အစီရင်ခံစာ',
        start_date: 'စတင်ရက်စွဲ',
        end_date: 'ပြီးဆုံးရက်စွဲ',
        generate_report: 'အစီရင်ခံစာထုတ်ရန်',
        export_to_excel: 'Excel သို့ ထုတ်ရန်',
        settings_management: 'ဆက်တင်များ',
        company_information: 'ကုမ္ပဏီအချက်အလက်',
        company_name: 'ကုမ္ပဏီအမည်',
        company_logo: 'ကုမ္ပဏီလိုဂို',
        save_company_info: 'ကုမ္ပဏီအချက်အလက် သိမ်းဆည်းရန်',
        system_settings: 'စနစ်ဆက်တင်များ',
        language: 'ဘာသာစကား',
        currency: 'ငွေကြေး',
        tax_rate: 'အခွန် (%)',
        enable_notifications: 'အသိပေးချက်များ ဖွင့်ရန်',
        enable_sound_effects: 'အသံဖွင့်ရန်',
        save_system_settings: 'စနစ်ဆက်တင်များ သိမ်းဆည်းရန်',
        export_backup_json: 'အရန်ဒေတာထုတ်ရန် (JSON)',
        import_backup_json: 'အရန်ဒေတာထည့်ရန် (JSON)',
        reset_data: 'ဒေတာပြန်လည်သတ်မှတ်ရန်',
        report_results: 'အစီရင်ခံစာ ရလဒ်များ',
        generate_report_to_see_results: 'ရလဒ်များကြည့်ရန် အစီရင်ခံစာထုတ်ပါ',
        business_type: 'လုပ်ငန်းအမျိုးအစား',
        clothing_business: 'အဝတ်အထည်',
        pharmacy_business: 'ဆေးဆိုင်',
        convenience_business: 'အဆင်ပြေဆိုင်',
        hardware_business: 'သံထည်ဆိုင်',
        footer_text: '© 2024 Swift POS. မူပိုင်ခွင့်များရယူပြီး။',
        scan_barcode_title: 'ဘားကုဒ်စကင်ဖတ်ပါ',
        btn_close_scanner: 'စကင်နာပိတ်ရန်',
        btn_scan_barcode: 'စကင်ဖတ်',
        barcode_detected: 'ဘားကုဒ်တွေ့ရှိသည်',
        product_found_and_loaded: 'ကုန်ပစ္စည်းကိုတွေ့ရှိပြီး တည်းဖြတ်ရန်အတွက် တင်ထားပါသည်။',
        actions: 'လုပ်ဆောင်ချက်များ',
        'Category Management': 'အမျိုးအစား စီမံခန့်ခွဲမှု',
        'Add New Category': 'အမျိုးအစားသစ်ထည့်ရန်',
        'Update Category': 'အမျိုးအစား အသစ်ပြင်ဆင်ရန်',
        'Category Name': 'အမျိုးအစားအမည်',
        'Are you sure you want to delete this category?': 'ဤအမျိုးအစားကို ဖျက်ရန် သေချာပါသလား။',
        'expenses_by_category': 'အမျိုးအစားအလိုက် ကုန်ကျစရိတ်',
        'recent_supplier_payments': 'မကြာသေးမီက ကုန်သွင်းသူ ငွေပေးချေမှုများ',
        'Payment History for': 'အတွက် ငွေပေးချေမှု မှတ်တမ်း',
        'View Payments': 'ငွေပေးချေမှုများ ကြည့်ရန်',
        'No payments found.': 'ငွေပေးချေမှုများ မတွေ့ပါ။',
        'Total COGS': 'ရောင်းကုန်ပစ္စည်းများ၏ စုစုပေါင်းကုန်ကျစရိတ်',
        'Gross Profit': 'စုစုပေါင်းအမြတ်',
        'Total Expenses': 'စုစုပေါင်း ကုန်ကျစရိတ်',
        'Net Profit': 'အသားတင်အမြတ်',
        'Report for': 'အတွက် အစီရင်ခံစာ',
        'Inventory Value': 'ကုန်ပစ္စည်းတန်ဖိုး',
        'Select Supplier': 'ကုန်သွင်းသူ ရွေးရန်',
        'Edit': 'ပြင်ဆင်ရန်',
        'Delete': 'ဖျက်ရန်',
        'Go to Settings to add categories.': 'အမျိုးအစားများထည့်ရန် ဆက်တင်များသို့ သွားပါ။',
        'Enter new category name': 'အမျိုးအစားအမည်အသစ် ထည့်ပါ',
        'Cancel': 'မလုပ်တော့ပါ',
        'Save': 'သိမ်းဆည်းရန်',
        'record_payment': 'ငွေပေးချေမှု မှတ်တမ်းတင်ရန်',
        'add_payment': 'ငွေပေးချေမှု ထည့်ရန်',
        'new_payment_for': 'အတွက် ငွေပေးချေမှုအသစ်',
        'customer_credit_balance': 'အကြွေး လက်ကျန်',
        'total_credit': 'စုစုပေါင်း အကြွေး',
        'total_paid': 'စုစုပေါင်း ပေးချေပြီး',
        'balance': 'လက်ကျန်',
        'credit_history': 'အကြွေး မှတ်တမ်း',
        'credit_sale_customer_required': 'အကြွေးရောင်းရန်အတွက် မှတ်ပုံတင်ထားသော ဖောက်သည်ကို ရွေးချယ်ရပါမည်။',
        'supplier_payment_form': 'ကုန်သွင်းသူ ငွေပေးချေမှု မှတ်တမ်းတင်ရန်',
        'payment_to': 'သို့ ငွေပေးချေရန်',
        'credit_sales': 'အကြွေးရောင်းခြင်း',
        'customer_payments': 'ဖောက်သည် ငွေပေးချေမှုများ',
        'No payments recorded.': 'ငွေပေးချေမှု မှတ်တမ်းမရှိပါ။',
        'low_stock_threshold': 'စတော့နည်း ကန့်သတ်ချက်',
        'purchase_suggestions': 'ဝယ်ယူရန် အကြံပြုချက်များ',
        'current_stock': 'လက်ရှိ စတော့',
        'record_customer_payment': 'ဖောက်သည်ငွေပေးချေမှု မှတ်တမ်းတင်ရန်',
        'No low stock products.': 'စတော့နည်းသော ကုန်ပစ္စည်းများ မရှိပါ။',
        'Select Customer': 'ဖောက်သည် ရွေးရန်',
        'Add Customer': 'ဖောက်သည် အသစ်ထည့်ရန်',
        'Edit Customer': 'ဖောက်သည် ပြင်ဆင်ရန်',
        receipt_settings: 'ပြေစာ ဆက်တင်များ',
        receipt_size: 'ပြေစာ အရွယ်အစား',
        standard_print: 'ပုံမှန် (A4/Letter)',
        thermal_80mm: '80mm အပူစနစ် ပရင်တာ',
        thermal_58mm: '58mm အပူစနစ် ပရင်တာ',
        receipt_footer_text: 'ပြေစာ အောက်ခြေစာသား',
        todays_sales: 'ယနေ့ အရောင်းများ',
        void_sale: 'ပယ်ဖျက်ရန်',
        load_to_cart_for_edit: 'ဤသည်မှာ မူလအရောင်းကို ပယ်ဖျက်ပြီး ပစ္စည်းများကို တည်းဖြတ်ရန်အတွက် ဈေးဝယ်လှည်းထဲသို့ ထည့်သွင်းပါမည်။ ဆက်လုပ်မည်လား။',
        are_you_sure_void_sale: 'ဤအရောင်းကို ပယ်ဖျက်ရန် သေချာပါသလား။ ဤသည်မှာ ပစ္စည်းများကို ပြန်လည်စတော့သွင်းမည် ဖြစ်ပြီး ပြန်ပြင်၍မရပါ။',
        sale_voided_successfully: 'အရောင်းကို အောင်မြင်စွာ ပယ်ဖျက်ပြီးပါပြီ။',
        sale_loaded_for_edit: 'တည်းဖြတ်ရန်အတွက် အရောင်းကို ဈေးဝယ်လှည်းထဲသို့ ထည့်ပြီးပါပြီ။',
        edit_expense: 'ကုန်ကျစရိတ် ပြင်ဆင်ရန်',
        confirm_delete_expense: 'ဤကုန်ကျစရိတ်ကို ဖျက်ရန် သေချာပါသလား။',
        customer_details: 'ဖောက်သည် အချက်အလက်',
        items_purchased: 'ဝယ်ယူခဲ့သော ပစ္စည်းများ',
        total_amount: 'စုစုပေါင်း ပမာဏ',
        confirm_void: 'ပယ်ဖျက်ရန် အတည်ပြုပါ',
        folder_selection_disabled_in_environment: 'ဤ sandboxed ပတ်ဝန်းကျင်တွင် ဖိုလ်ဒါရွေးချယ်မှုကို ပိတ်ထားသည်။ အရန်သိမ်းဖိုင်များကို ပုံမှန်အတိုင်း ဒေါင်းလုဒ်လုပ်ပါမည်။',
        storage_preferences: 'ဒေတာသိုလှောင်မှု ဦးစားပေးများ',
        local_folder: 'ပြည်တွင်း ဖိုလ်ဒါ',
        online_folder_url: 'အွန်လိုင်း ဖိုလ်ဒါ (URL)',
        path_or_url: 'လမ်းကြောင်း သို့မဟုတ် URL',
        choose_folder: 'ဖိုလ်ဒါ ရွေးရန်',
        save_storage_preference: 'သိုလှောင်မှု ဦးစားပေးကို သိမ်းဆည်းရန်',
        path_or_url_placeholder: '/Users/me/Documents သို့မဟုတ် https://drive.google.com/...',
        data_management: 'ဒေတာ စီမံခန့်ခွဲမှု',
        sales_history: 'အရောင်းမှတ်တမ်း',
        no_sales_found_for_period: 'ရွေးချယ်ထားသောကာလအတွက် အရောင်းမှတ်တမ်း မရှိပါ။',
        all_categories: 'အမျိုးအစားအားလုံး',
        date_range: 'ရက်စွဲအပိုင်းအခြား',
    }
};

interface LanguageContextType {
    language: string;
    setLanguage: (language: string) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState(() => {
        return localStorage.getItem('language') || 'en';
    });

    useEffect(() => {
        if (language === 'my') {
            document.body.classList.add('myanmar-font');
        } else {
            document.body.classList.remove('myanmar-font');
        }
        localStorage.setItem('language', language);
    }, [language]);
    
    const setLanguage = (lang: string) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        return translations[language]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
